/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package kotlin.internal

/**
 * Specifies that usages of this internal standard-library declaration may be generated by the
 * compiler. This target-bootstrap declaration mirrors the Common stdlib annotation.
 */
@Retention(AnnotationRetention.BINARY)
internal annotation class UsedFromCompilerGeneratedCode
