/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.cli;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.TestGeneratorForTestsIntegrationTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/cli/dotnet")
@TestDataPath("$PROJECT_ROOT")
public class DotNetCliTestGenerated extends AbstractCliTest {
  private void run(String fileName) {
    doDotNetTest("compiler/testData/cli/dotnet/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDotnet() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/cli/dotnet"), Pattern.compile("^(.+)\\.args$"), null, false);
  }

  @Test
  @TestMetadata("callableExport.args")
  public void testCallableExport() {
    run("callableExport.args");
  }

  @Test
  @TestMetadata("callableExportDefaultClash.args")
  public void testCallableExportDefaultClash() {
    run("callableExportDefaultClash.args");
  }

  @Test
  @TestMetadata("callableExportInvalid.args")
  public void testCallableExportInvalid() {
    run("callableExportInvalid.args");
  }

  @Test
  @TestMetadata("callableExportNullableParameter.args")
  public void testCallableExportNullableParameter() {
    run("callableExportNullableParameter.args");
  }

  @Test
  @TestMetadata("callableExportReservedNullableAttribute.args")
  public void testCallableExportReservedNullableAttribute() {
    run("callableExportReservedNullableAttribute.args");
  }

  @Test
  @TestMetadata("destinationDirectory.args")
  public void testDestinationDirectory() {
    run("destinationDirectory.args");
  }

  @Test
  @TestMetadata("dotnetTargetInvalid.args")
  public void testDotnetTargetInvalid() {
    run("dotnetTargetInvalid.args");
  }

  @Test
  @TestMetadata("dotnetTargetNet.args")
  public void testDotnetTargetNet() {
    run("dotnetTargetNet.args");
  }

  @Test
  @TestMetadata("emptyMain.args")
  public void testEmptyMain() {
    run("emptyMain.args");
  }

  @Test
  @TestMetadata("helloWorld.args")
  public void testHelloWorld() {
    run("helloWorld.args");
  }

  @Test
  @TestMetadata("missingDestination.args")
  public void testMissingDestination() {
    run("missingDestination.args");
  }

  @Test
  @TestMetadata("moduleName.args")
  public void testModuleName() {
    run("moduleName.args");
  }

  @Test
  @TestMetadata("plainFunctionExportPrimitiveReserved.args")
  public void testPlainFunctionExportPrimitiveReserved() {
    run("plainFunctionExportPrimitiveReserved.args");
  }

  @Test
  @TestMetadata("printlnEscapedString.args")
  public void testPrintlnEscapedString() {
    run("printlnEscapedString.args");
  }

  @Test
  @TestMetadata("printlnNoArguments.args")
  public void testPrintlnNoArguments() {
    run("printlnNoArguments.args");
  }
}
