/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators

import templates.Aggregates
import templates.COPYRIGHT_NOTICE
import templates.Elements
import templates.Family
import templates.KotlinTarget
import templates.MemberTemplate
import templates.Numeric
import templates.PrimitiveType
import templates.autoGeneratedWarning
import java.io.File
import java.io.StringWriter
import kotlin.system.exitProcess

/**
 * Materializes only the Common collection templates whose dependency closure the experimental
 * Kotlin/.NET stdlib currently supports.
 *
 * This is a temporary source-product allowlist, not a .NET algorithm fork. Every emitted member
 * is built by the same Common template object used for the mature targets. Delete this generator
 * once Kotlin/.NET can compile the complete Common generated collection corpus.
 */
fun main(args: Array<String>) {
    if (args.size != 1) {
        println("Parameters:\n    <kotlin-base-dir>")
        exitProcess(1)
    }

    val baseDir = File(args.single())
    val outputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapCollections.kt"
    )
    val commonCollectionsFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/collections/Collections.kt")
    val commonCollectionsHeaderFile =
        baseDir.resolve("libraries/stdlib/common/src/kotlin/collections/CollectionsH.kt")
    val commonArraysFile =
        baseDir.resolve("libraries/stdlib/common/src/generated/_Arrays.kt")
    val arrayAsListDeclaration = extractCommonDeclaration(
        commonArraysFile,
        "public expect fun <T> Array<out T>.asList(): List<T>",
    )
    val lastIndexDeclaration = extractCommonDeclaration(
        commonCollectionsFile,
        "public val <T> List<T>.lastIndex: Int",
    )
    val checkIndexOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal expect fun checkIndexOverflow(index: Int): Int",
    )
    val checkCountOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal expect fun checkCountOverflow(count: Int): Int",
    )
    val throwIndexOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal fun throwIndexOverflow()",
    )
    val throwCountOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal fun throwCountOverflow()",
    )
    val collectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun collectionToArray(collection: Collection<*>): Array<Any?>",
    )
    val typedCollectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun <T> collectionToArray(collection: Collection<*>, array: Array<T>): Array<T>",
    )
    val arrayOfNullsFromReferenceDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun <T> arrayOfNulls(reference: Array<T>, size: Int): Array<T>",
    )
    val collectionToArrayImplementation = extractCommonFunction(
        commonCollectionsFile,
        "internal fun collectionToArrayCommonImpl(collection: Collection<*>): Array<Any?>",
    )
    val typedCollectionToArrayImplementation = extractCommonFunction(
        commonCollectionsFile,
        "internal fun <T> collectionToArrayCommonImpl(collection: Collection<*>, array: Array<T>): Array<T>",
    )
    val terminateCollectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsFile,
        "internal expect fun <T> terminateCollectionToArray(collectionSize: Int, array: Array<T>): Array<T>",
    )
    val selectedTemplates = sequenceOf(
        Aggregates.f_all selectedFor setOf(Family.Iterables),
        Aggregates.f_any selectedFor setOf(Family.Iterables),
        Aggregates.f_any_predicate selectedFor setOf(Family.Iterables),
        Aggregates.f_count selectedFor setOf(Family.Iterables),
        Aggregates.f_fold selectedFor setOf(Family.Iterables),
        Aggregates.f_foldIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_foldRight selectedFor setOf(Family.Lists),
        Aggregates.f_foldRightIndexed selectedFor setOf(Family.Lists),
        Aggregates.f_none selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceIndexedSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceIndexedOrNullSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceOrNullSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceRightSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightIndexedSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightIndexedOrNullSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightOrNullSuper selectedFor setOf(Family.Lists),
        Elements.f_contains selectedFor setOf(Family.Iterables),
        Elements.f_elementAtOrNull selectedFor setOf(Family.Iterables),
        Elements.f_first selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_firstOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_getOrNull selectedFor setOf(Family.Lists),
        Elements.f_indexOf selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_indexOfFirst selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_indexOfLast selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_last selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastIndexOf selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_single selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_singleOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        (Numeric.f_sum selectedFor setOf(Family.Iterables))
            .limitedTo(PrimitiveType.numericPrimitives),
    )
    val members = selectedTemplates
        .flatMap { selection ->
            selection.template.instantiate(listOf(KotlinTarget.Common)).filter { member ->
                member.family in selection.families &&
                        (selection.primitives == null || member.primitive in selection.primitives)
            }
        }
        .sortedBy { it.sortingSignature }
        .toList()

    val generatedSource = StringWriter()
    generatedSource.appendLine(COPYRIGHT_NOTICE)
    generatedSource.appendLine("package kotlin.collections")
    generatedSource.appendLine()
    generatedSource.appendLine(autoGeneratedWarning("GenerateDotNetBootstrapCollections.kt"))
    generatedSource.appendLine(arrayAsListDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(lastIndexDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(checkIndexOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(checkCountOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(throwIndexOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(throwCountOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(collectionToArrayDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(typedCollectionToArrayDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(arrayOfNullsFromReferenceDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(collectionToArrayImplementation)
    generatedSource.appendLine()
    generatedSource.appendLine(typedCollectionToArrayImplementation)
    generatedSource.appendLine()
    generatedSource.appendLine(terminateCollectionToArrayDeclaration)
    generatedSource.appendLine()
    for (member in members) {
        member.build(generatedSource)
    }
    val normalizedSource = generatedSource.toString()
        .replace("\r\n", "\n")
        .lineSequence()
        .joinToString("\n") { line -> line.trimEnd() }
        .trimEnd() + "\n"
    outputFile.parentFile.mkdirs()
    outputFile.writeText(normalizedSource, Charsets.UTF_8)
}

private data class SelectedTemplate(
    val template: MemberTemplate,
    val families: Set<Family>,
    val primitives: Set<PrimitiveType>? = null,
)

private infix fun MemberTemplate.selectedFor(families: Set<Family>): SelectedTemplate =
    SelectedTemplate(this, families)

private fun SelectedTemplate.limitedTo(primitives: Set<PrimitiveType>): SelectedTemplate =
    copy(primitives = primitives)

/**
 * Copies one complete declaration from an authoritative Common source file. The unique declaration
 * header is deliberately a hard generation contract: upstream movement or signature changes fail
 * instead of leaving the bootstrap projection silently stale.
 */
private fun extractCommonDeclaration(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val documentationIndex = source.lastIndexOf("/**", declarationIndex)
    check(documentationIndex >= 0) {
        "Cannot find KDoc for Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val nextDocumentationIndex = source.indexOf("\n/**", declarationIndex)
    check(nextDocumentationIndex >= 0) {
        "Cannot find the end of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    return source.substring(documentationIndex, nextDocumentationIndex).trimEnd()
}

/**
 * Copies one annotation-led declaration that intentionally has no KDoc. Blank declaration
 * boundaries are part of the fail-closed contract, so an upstream regrouping requires review.
 */
private fun extractCommonUndocumentedDeclaration(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val declarationStart = source.lastIndexOf("\n\n", declarationIndex)
    check(declarationStart >= 0) {
        "Cannot find the start of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val declarationEnd = source.indexOf("\n\n", declarationIndex)
    check(declarationEnd >= 0) {
        "Cannot find the end of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    return source.substring(declarationStart + 2, declarationEnd).trimEnd()
}

/** Copies one complete single-line declaration and rejects any unexpected trailing source. */
private fun extractCommonSingleLineDeclaration(sourceFile: File, declaration: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declaration)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declaration' in ${sourceFile.path}"
    }
    check(source.indexOf(declaration, declarationIndex + declaration.length) < 0) {
        "Common declaration '$declaration' is not unique in ${sourceFile.path}"
    }
    val lineStart = source.lastIndexOf('\n', declarationIndex - 1) + 1
    val lineEnd = source.indexOf('\n', declarationIndex).takeIf { it >= 0 } ?: source.length
    check(source.substring(lineStart, lineEnd) == declaration) {
        "Common declaration '$declaration' is no longer one complete line in ${sourceFile.path}"
    }
    return declaration
}

/**
 * Copies one complete block-bodied function from authoritative Common source. The unique header
 * and balanced body are fail-closed generation contracts; the .NET source product does not own a
 * second spelling of the algorithm.
 */
private fun extractCommonFunction(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common function '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common function header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val bodyStart = source.indexOf('{', declarationIndex + declarationHeader.length)
    check(bodyStart >= 0) {
        "Cannot find Common function body for '$declarationHeader' in ${sourceFile.path}"
    }
    var depth = 0
    for (index in bodyStart until source.length) {
        when (source[index]) {
            '{' -> depth++
            '}' -> {
                depth--
                check(depth >= 0) {
                    "Unbalanced Common function body for '$declarationHeader' in ${sourceFile.path}"
                }
                if (depth == 0) {
                    return source.substring(declarationIndex, index + 1).trimEnd()
                }
            }
        }
    }
    error("Unterminated Common function body for '$declarationHeader' in ${sourceFile.path}")
}
