/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators

import templates.Aggregates
import templates.COPYRIGHT_NOTICE
import templates.Elements
import templates.Family
import templates.Guards
import templates.KotlinTarget
import templates.MemberTemplate
import templates.Numeric
import templates.PrimitiveType
import templates.SequenceOps
import templates.StringJoinOps
import templates.autoGeneratedWarning
import java.io.File
import java.io.StringWriter
import kotlin.system.exitProcess

/**
 * Materializes only the Common collection templates whose dependency closure the experimental
 * Kotlin/.NET stdlib currently supports.
 *
 * This is a temporary source-product allowlist, not a .NET algorithm fork. Every emitted member
 * is built by the same Common template object used for the mature targets. Delete this generator
 * once Kotlin/.NET can compile the complete Common generated collection corpus.
 */
fun main(args: Array<String>) {
    if (args.size != 1) {
        println("Parameters:\n    <kotlin-base-dir>")
        exitProcess(1)
    }

    val baseDir = File(args.single())
    val outputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapCollections.kt"
    )
    val appendableOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapAppendable.kt"
    )
    val stringBuilderOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapStringBuilder.kt"
    )
    val kotlinOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapKotlin.kt"
    )
    val enumEntriesOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapEnumEntries.kt"
    )
    val enumOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapEnum.kt"
    )
    val jsNameOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapJsName.kt"
    )
    val commonCollectionsFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/collections/Collections.kt")
    val commonCollectionsHeaderFile =
        baseDir.resolve("libraries/stdlib/common/src/kotlin/collections/CollectionsH.kt")
    val commonArraysFile =
        baseDir.resolve("libraries/stdlib/common/src/generated/_Arrays.kt")
    val commonAppendableFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/text/Appendable.kt")
    val commonStringBuilderFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/text/StringBuilder.kt")
    val commonStandardFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/util/Standard.kt")
    val commonEnumEntriesFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/enums/EnumEntries.kt")
    val commonEnumFile = baseDir.resolve("libraries/stdlib/src/kotlin/Enum.kt")
    val commonJsAnnotationsFile =
        baseDir.resolve("libraries/stdlib/common/src/kotlin/JsAnnotationsH.kt")
    val arrayAsListDeclaration = extractCommonDeclaration(
        commonArraysFile,
        "public expect fun <T> Array<out T>.asList(): List<T>",
    )
    val lastIndexDeclaration = extractCommonDeclaration(
        commonCollectionsFile,
        "public val <T> List<T>.lastIndex: Int",
    )
    val checkIndexOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal expect fun checkIndexOverflow(index: Int): Int",
    )
    val checkCountOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal expect fun checkCountOverflow(count: Int): Int",
    )
    val throwIndexOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal fun throwIndexOverflow()",
    )
    val throwCountOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal fun throwCountOverflow()",
    )
    val collectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun collectionToArray(collection: Collection<*>): Array<Any?>",
    )
    val randomAccessDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "public expect interface RandomAccess",
    )
    val typedCollectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun <T> collectionToArray(collection: Collection<*>, array: Array<T>): Array<T>",
    )
    val arrayOfNullsFromReferenceDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun <T> arrayOfNulls(reference: Array<T>, size: Int): Array<T>",
    )
    val collectionToArrayImplementation = extractCommonFunction(
        commonCollectionsFile,
        "internal fun collectionToArrayCommonImpl(collection: Collection<*>): Array<Any?>",
    )
    val typedCollectionToArrayImplementation = extractCommonFunction(
        commonCollectionsFile,
        "internal fun <T> collectionToArrayCommonImpl(collection: Collection<*>, array: Array<T>): Array<T>",
    )
    val terminateCollectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsFile,
        "internal expect fun <T> terminateCollectionToArray(collectionSize: Int, array: Array<T>): Array<T>",
    )
    val iterableSumOfInt = Aggregates.f_sumOf().singleCommonTemplate(
        family = Family.Iterables,
        signature = "sumOf(selector: (T) -> Int)",
    )
    val selectedTemplates = sequenceOf(
        Aggregates.f_all selectedFor setOf(Family.Iterables),
        Aggregates.f_any selectedFor setOf(Family.Iterables),
        Aggregates.f_any_predicate selectedFor setOf(Family.Iterables),
        Aggregates.f_count selectedFor setOf(Family.Iterables, Family.Collections),
        Aggregates.f_count_predicate selectedFor setOf(Family.Iterables),
        Aggregates.f_fold selectedFor setOf(Family.Iterables),
        Aggregates.f_foldIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_foldRight selectedFor setOf(Family.Lists),
        Aggregates.f_foldRightIndexed selectedFor setOf(Family.Lists),
        Aggregates.f_forEach selectedFor setOf(Family.Iterables),
        Aggregates.f_forEachIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_none selectedFor setOf(Family.Iterables),
        Aggregates.f_none_predicate selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceIndexedSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceIndexedOrNullSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceOrNullSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceRightSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightIndexedSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightIndexedOrNullSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightOrNullSuper selectedFor setOf(Family.Lists),
        Aggregates.f_sumBy selectedFor setOf(Family.Iterables),
        Aggregates.f_sumByDouble selectedFor setOf(Family.Iterables),
        iterableSumOfInt selectedFor setOf(Family.Iterables),
        Elements.f_contains selectedFor setOf(Family.Iterables),
        Elements.f_elementAt selectedFor setOf(Family.Lists),
        Elements.f_elementAtOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_find selectedFor setOf(Family.Iterables),
        Elements.f_findLast selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_first selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_firstNotNullOf selectedFor setOf(Family.Iterables),
        Elements.f_firstNotNullOfOrNull selectedFor setOf(Family.Iterables),
        Elements.f_first_predicate selectedFor setOf(Family.Iterables),
        Elements.f_firstOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_firstOrNull_predicate selectedFor setOf(Family.Iterables),
        Elements.f_getOrNull selectedFor setOf(Family.Lists, Family.ArraysOfObjects),
        Elements.f_indexOf selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_indexOfFirst selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_indexOfLast selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_last selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_last_predicate selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastIndexOf selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastOrNull_predicate selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_single selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_single_predicate selectedFor setOf(Family.Iterables),
        Elements.f_singleOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_singleOrNull_predicate selectedFor setOf(Family.Iterables),
        Guards.f_requireNoNulls selectedFor setOf(Family.Iterables, Family.Lists),
        (Numeric.f_average selectedFor setOf(Family.Iterables))
            .limitedTo(PrimitiveType.numericPrimitives),
        (Numeric.f_sum selectedFor setOf(Family.Iterables))
            .limitedTo(PrimitiveType.numericPrimitives),
        SequenceOps.f_asIterable selectedFor setOf(Family.Iterables),
        StringJoinOps.f_joinTo selectedFor setOf(Family.Iterables),
        StringJoinOps.f_joinToString selectedFor setOf(Family.Iterables),
    ) + Elements.f_components.asSequence().map { component ->
        component selectedFor setOf(Family.Lists)
    }
    val members = selectedTemplates
        .flatMap { selection ->
            selection.template.instantiate(listOf(KotlinTarget.Common)).filter { member ->
                member.family in selection.families &&
                        (selection.primitives == null || member.primitive in selection.primitives)
            }
        }
        .sortedBy { it.sortingSignature }
        .toList()

    val generatedSource = StringWriter()
    generatedSource.appendLine(COPYRIGHT_NOTICE)
    generatedSource.appendLine("package kotlin.collections")
    generatedSource.appendLine()
    generatedSource.appendLine(autoGeneratedWarning("GenerateDotNetBootstrapCollections.kt"))
    generatedSource.appendLine(arrayAsListDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(lastIndexDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(randomAccessDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(checkIndexOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(checkCountOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(throwIndexOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(throwCountOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(collectionToArrayDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(typedCollectionToArrayDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(arrayOfNullsFromReferenceDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(collectionToArrayImplementation)
    generatedSource.appendLine()
    generatedSource.appendLine(typedCollectionToArrayImplementation)
    generatedSource.appendLine()
    generatedSource.appendLine(terminateCollectionToArrayDeclaration)
    generatedSource.appendLine()
    for (member in members) {
        member.build(generatedSource)
    }
    generatedSource.appendLine(
        """
        /**
         * Private resolution marker for the exact Common `Array.getOrNull` body above.
         *
         * The shared range-contains lowering consumes every call before CIL generation. This is
         * intentionally not a public `Array.indices` product: publishing that property requires
         * the complete `IntRange` dependency closure, which is outside this bootstrap slice.
         */
        private val <T> Array<out T>.indices: IntRange
            get() = throw AssertionError("Array.indices bootstrap marker survived lowering")
        """.trimIndent()
    )
    val normalizedSource = generatedSource.toString()
        .replace("\r\n", "\n")
        .lineSequence()
        .joinToString("\n") { line -> line.trimEnd() }
        .trimEnd() + "\n"
    outputFile.parentFile.mkdirs()
    outputFile.writeText(normalizedSource, Charsets.UTF_8)

    appendableOutputFile.writeText(
        projectWholeCommonFile(commonAppendableFile),
        Charsets.UTF_8,
    )
    stringBuilderOutputFile.writeText(
        projectStringBuilderFile(commonStringBuilderFile),
        Charsets.UTF_8,
    )
    kotlinOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin",
            declarations = listOf(
                extractCommonDeclaration(
                    commonStandardFile,
                    "public class NotImplementedError(message: String = \"An operation is not implemented.\") : Error(message)",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
    enumEntriesOutputFile.writeText(
        projectEnumEntriesFile(commonEnumEntriesFile),
        Charsets.UTF_8,
    )
    enumOutputFile.writeText(
        projectEnumFile(commonEnumFile),
        Charsets.UTF_8,
    )
    jsNameOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin.js",
            imports = listOf("kotlin.annotation.AnnotationTarget.*"),
            declarations = listOf(
                extractCommonDeclaration(
                    commonJsAnnotationsFile,
                    "public expect annotation class JsName(val name: String)",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
}

private fun projectEnumFile(sourceFile: File): String {
    var projectedSource = sourceFile.readText().replace("\r\n", "\n")
    val commonConstructor =
        "public expect abstract class Enum<E : Enum<E>>(name: String, ordinal: Int): Comparable<E> {"
    val bootstrapConstructor =
        "public expect abstract class Enum<E : Enum<E>>(name: String = \"\", ordinal: Int = -1): Comparable<E> {"
    check(projectedSource.countOccurrences(commonConstructor) == 1) {
        "Expected exactly one Common Enum constructor in ${sourceFile.path}"
    }
    // A serialized Enum constructor is deserialized by FIR with synthetic defaults regardless
    // of its proto flags. The temporary same-compilation source product has no deserialization
    // boundary, so express those two frontend-only placeholders in source. The enum lowering
    // always replaces them with the exact entry name and ordinal; no physical default stub may
    // survive. Remove this projection when the stdlib is always consumed as an installed KLIB.
    projectedSource = projectedSource.replace(commonConstructor, bootstrapConstructor)
    return injectGeneratedWarning(projectedSource)
}

private fun projectEnumEntriesFile(sourceFile: File): String {
    var projectedSource = sourceFile.readText().replace("\r\n", "\n")
    val commonFileSuppression =
        "@file:Suppress(\"EXPECT_AND_ACTUAL_IN_THE_SAME_MODULE\") // for building kotlin-stdlib-jvm-minimal-for-test"
    check(projectedSource.countOccurrences(commonFileSuppression) == 1) {
        "Expected exactly one Common EnumEntries file suppression in ${sourceFile.path}"
    }
    // This suppression belongs to the JVM minimal-test source layout. The .NET common/platform
    // split has no same-module expect/actual declaration and its test harness correctly rejects
    // suppressing an error diagnostic in injected bootstrap source.
    projectedSource = projectedSource.replace(commonFileSuppression, "")
    val reifiedSurface = extractCommonDeclarationPrefix(
        sourceFile,
        "public inline fun <reified T : Enum<T>> enumEntries(): EnumEntries<T>",
        "@PublishedApi\n@SinceKotlin(\"1.8\") // Used by pre-1.9.0 JVM compiler for the feature in preview mode.",
    )
    check(projectedSource.countOccurrences(reifiedSurface) == 1) {
        "Expected exactly one reified enum-entries surface in ${sourceFile.path}"
    }
    projectedSource = projectedSource.replace(reifiedSurface, "")
    return injectGeneratedWarning(projectedSource)
}

/**
 * Copies a documented declaration plus its immediately following declarations up to one exact
 * retained declaration prefix. This is used for Common source tails where the ordinary next-KDoc
 * boundary does not exist; both markers stay fail-closed under upstream regrouping.
 */
private fun extractCommonDeclarationPrefix(
    sourceFile: File,
    declarationHeader: String,
    retainedDeclarationPrefix: String,
): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val documentationIndex = source.lastIndexOf("/**", declarationIndex)
    check(documentationIndex >= 0) {
        "Cannot find KDoc for Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val retainedDeclarationIndex = source.indexOf(retainedDeclarationPrefix, declarationIndex)
    check(retainedDeclarationIndex >= 0) {
        "Cannot find retained Common declaration prefix '$retainedDeclarationPrefix' in ${sourceFile.path}"
    }
    check(source.indexOf(retainedDeclarationPrefix, retainedDeclarationIndex + retainedDeclarationPrefix.length) < 0) {
        "Retained Common declaration prefix '$retainedDeclarationPrefix' is not unique in ${sourceFile.path}"
    }
    return source.substring(documentationIndex, retainedDeclarationIndex).trimEnd()
}

private fun projectWholeCommonFile(sourceFile: File): String {
    val normalizedSource = sourceFile.readText().replace("\r\n", "\n")
    return injectGeneratedWarning(normalizedSource)
}

private fun projectStringBuilderFile(sourceFile: File): String {
    var projectedSource = sourceFile.readText().replace("\r\n", "\n")
    val contractsImport = "import kotlin.contracts.*\n"
    check(projectedSource.countOccurrences(contractsImport) == 1) {
        "Expected exactly one contracts import in ${sourceFile.path}"
    }
    projectedSource = projectedSource.replace(contractsImport, "")
    for (declarationHeader in listOf(
        "public inline fun buildString(builderAction: StringBuilder.() -> Unit): String",
        "public inline fun buildString(capacity: Int, builderAction: StringBuilder.() -> Unit): String",
    )) {
        val declaration = extractCommonDeclaration(sourceFile, declarationHeader)
        check(projectedSource.countOccurrences(declaration) == 1) {
            "Expected exactly one projected Common declaration '$declarationHeader' in ${sourceFile.path}"
        }
        projectedSource = projectedSource.replace(declaration, "")
    }
    return injectGeneratedWarning(projectedSource)
}

private fun injectGeneratedWarning(source: String): String {
    val packageMarker = "package "
    val packageIndex = source.indexOf(packageMarker)
    check(packageIndex >= 0) { "Projected Common source has no package declaration" }
    val packageLineEnd = source.indexOf('\n', packageIndex)
    check(packageLineEnd >= 0) { "Projected Common source has an unterminated package declaration" }
    val warning = autoGeneratedWarning("GenerateDotNetBootstrapCollections.kt").trimEnd()
    return (source.substring(0, packageLineEnd + 1) + "\n" + warning + "\n" + source.substring(packageLineEnd + 1))
        .lineSequence()
        .joinToString("\n") { line -> line.trimEnd() }
        .trimEnd() + "\n"
}

private fun buildProjectedSource(
    packageName: String,
    imports: List<String> = emptyList(),
    declarations: List<String>,
): String = buildString {
    appendLine(COPYRIGHT_NOTICE)
    appendLine("package $packageName")
    appendLine()
    appendLine(autoGeneratedWarning("GenerateDotNetBootstrapCollections.kt"))
    for (importName in imports) appendLine("import $importName")
    if (imports.isNotEmpty()) appendLine()
    append(declarations.joinToString("\n\n"))
    appendLine()
}.lineSequence()
    .joinToString("\n") { line -> line.trimEnd() }
    .trimEnd() + "\n"

private fun String.countOccurrences(needle: String): Int {
    check(needle.isNotEmpty())
    var count = 0
    var fromIndex = 0
    while (true) {
        val index = indexOf(needle, fromIndex)
        if (index < 0) return count
        count++
        fromIndex = index + needle.length
    }
}

private data class SelectedTemplate(
    val template: MemberTemplate,
    val families: Set<Family>,
    val primitives: Set<PrimitiveType>? = null,
)

private infix fun MemberTemplate.selectedFor(families: Set<Family>): SelectedTemplate =
    SelectedTemplate(this, families)

private fun SelectedTemplate.limitedTo(primitives: Set<PrimitiveType>): SelectedTemplate =
    copy(primitives = primitives)

/** Selects one overload template by its exact authoritative Common family/signature pair. */
private fun List<MemberTemplate>.singleCommonTemplate(
    family: Family,
    signature: String,
): MemberTemplate {
    val matches = filter { template ->
        template.instantiate(listOf(KotlinTarget.Common)).any { member ->
            member.family == family && member.signature == signature
        }
    }
    check(matches.size == 1) {
        "Expected one Common $family template '$signature', found ${matches.size}"
    }
    return matches.single()
}

/**
 * Copies one complete declaration from an authoritative Common source file. The unique declaration
 * header is deliberately a hard generation contract: upstream movement or signature changes fail
 * instead of leaving the bootstrap projection silently stale.
 */
private fun extractCommonDeclaration(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val documentationIndex = source.lastIndexOf("/**", declarationIndex)
    check(documentationIndex >= 0) {
        "Cannot find KDoc for Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val nextDocumentationIndex = source.indexOf("\n/**", declarationIndex)
    check(nextDocumentationIndex >= 0) {
        "Cannot find the end of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    return source.substring(documentationIndex, nextDocumentationIndex).trimEnd()
}

/**
 * Copies one annotation-led declaration that intentionally has no KDoc. Blank declaration
 * boundaries are part of the fail-closed contract, so an upstream regrouping requires review.
 */
private fun extractCommonUndocumentedDeclaration(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val declarationStart = source.lastIndexOf("\n\n", declarationIndex)
    check(declarationStart >= 0) {
        "Cannot find the start of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val declarationEnd = source.indexOf("\n\n", declarationIndex)
    check(declarationEnd >= 0) {
        "Cannot find the end of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    return source.substring(declarationStart + 2, declarationEnd).trimEnd()
}

/** Copies one complete single-line declaration and rejects any unexpected trailing source. */
private fun extractCommonSingleLineDeclaration(sourceFile: File, declaration: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declaration)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declaration' in ${sourceFile.path}"
    }
    check(source.indexOf(declaration, declarationIndex + declaration.length) < 0) {
        "Common declaration '$declaration' is not unique in ${sourceFile.path}"
    }
    val lineStart = source.lastIndexOf('\n', declarationIndex - 1) + 1
    val lineEnd = source.indexOf('\n', declarationIndex).takeIf { it >= 0 } ?: source.length
    check(source.substring(lineStart, lineEnd) == declaration) {
        "Common declaration '$declaration' is no longer one complete line in ${sourceFile.path}"
    }
    return declaration
}

/**
 * Copies one complete block-bodied function from authoritative Common source. The unique header
 * and balanced body are fail-closed generation contracts; the .NET source product does not own a
 * second spelling of the algorithm.
 */
private fun extractCommonFunction(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common function '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common function header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val bodyStart = source.indexOf('{', declarationIndex + declarationHeader.length)
    check(bodyStart >= 0) {
        "Cannot find Common function body for '$declarationHeader' in ${sourceFile.path}"
    }
    var depth = 0
    for (index in bodyStart until source.length) {
        when (source[index]) {
            '{' -> depth++
            '}' -> {
                depth--
                check(depth >= 0) {
                    "Unbalanced Common function body for '$declarationHeader' in ${sourceFile.path}"
                }
                if (depth == 0) {
                    return source.substring(declarationIndex, index + 1).trimEnd()
                }
            }
        }
    }
    error("Unterminated Common function body for '$declarationHeader' in ${sourceFile.path}")
}
