/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators

import templates.Aggregates
import templates.ArrayOps
import templates.COPYRIGHT_NOTICE
import templates.Elements
import templates.Family
import templates.Filtering
import templates.Generators
import templates.Guards
import templates.KotlinTarget
import templates.Mapping
import templates.MemberTemplate
import templates.Numeric
import templates.Ordering
import templates.PrimitiveType
import templates.SequenceOps
import templates.Snapshots
import templates.StringJoinOps
import templates.autoGeneratedWarning
import java.io.File
import java.io.StringWriter
import kotlin.system.exitProcess

/**
 * Materializes only the Common collection templates whose dependency closure the experimental
 * Kotlin/.NET stdlib currently supports.
 *
 * This is a temporary source-product allowlist, not a .NET algorithm fork. Every emitted member
 * is built by the same Common template object used for the mature targets. Delete this generator
 * once Kotlin/.NET can compile the complete Common generated collection corpus.
 */
fun main(args: Array<String>) {
    if (args.size != 1) {
        println("Parameters:\n    <kotlin-base-dir>")
        exitProcess(1)
    }

    val baseDir = File(args.single())
    val outputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapCollections.kt"
    )
    val appendableOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapAppendable.kt"
    )
    val stringBuilderOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapStringBuilder.kt"
    )
    val kotlinOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapKotlin.kt"
    )
    val enumEntriesOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapEnumEntries.kt"
    )
    val enumOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapEnum.kt"
    )
    val jsNameOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapJsName.kt"
    )
    val experimentalTypeInferenceOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapExperimentalTypeInference.kt"
    )
    val overloadResolutionByLambdaReturnTypeOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapOverloadResolutionByLambdaReturnType.kt"
    )
    val mutableCollectionsOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapMutableCollections.kt"
    )
    val preconditionsOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapPreconditions.kt"
    )
    val collectionFactoriesOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapCollectionFactories.kt"
    )
    val outOfMemoryErrorOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapOutOfMemoryError.kt"
    )
    val scalarBoundsOutputFile = baseDir.resolve(
        "libraries/stdlib/dotnet/common/src/generated/_DotNetBootstrapScalarBounds.kt"
    )
    val commonCollectionsFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/collections/Collections.kt")
    val commonCollectionsHeaderFile =
        baseDir.resolve("libraries/stdlib/common/src/kotlin/collections/CollectionsH.kt")
    val commonMutableCollectionsFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/collections/MutableCollections.kt")
    val commonPreconditionsFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/util/Preconditions.kt")
    val commonOutOfMemoryErrorFile =
        baseDir.resolve("libraries/stdlib/native-wasm/src/kotlin/Exceptions.kt")
    val commonArraysFile =
        baseDir.resolve("libraries/stdlib/common/src/generated/_Arrays.kt")
    val commonComparisonsFile =
        baseDir.resolve("libraries/stdlib/common/src/generated/_Comparisons.kt")
    val commonRangesFile =
        baseDir.resolve("libraries/stdlib/common/src/generated/_Ranges.kt")
    val commonAppendableFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/text/Appendable.kt")
    val commonStringBuilderFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/text/StringBuilder.kt")
    val commonStandardFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/util/Standard.kt")
    val commonEnumEntriesFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/enums/EnumEntries.kt")
    val commonEnumFile = baseDir.resolve("libraries/stdlib/src/kotlin/Enum.kt")
    val commonJsAnnotationsFile =
        baseDir.resolve("libraries/stdlib/common/src/kotlin/JsAnnotationsH.kt")
    val commonExperimentalTypeInferenceFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/experimental/inferenceMarker.kt")
    val commonInferenceAnnotationsFile =
        baseDir.resolve("libraries/stdlib/src/kotlin/annotations/Inference.kt")
    val arrayAsListDeclaration = extractCommonDeclaration(
        commonArraysFile,
        "public expect fun <T> Array<out T>.asList(): List<T>",
    )
    val lastIndexDeclaration = extractCommonDeclaration(
        commonCollectionsFile,
        "public val <T> List<T>.lastIndex: Int",
    )
    val checkIndexOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal expect fun checkIndexOverflow(index: Int): Int",
    )
    val checkCountOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal expect fun checkCountOverflow(count: Int): Int",
    )
    val throwIndexOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal fun throwIndexOverflow()",
    )
    val throwCountOverflowDeclaration = extractCommonUndocumentedDeclaration(
        commonCollectionsFile,
        "internal fun throwCountOverflow()",
    )
    val collectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun collectionToArray(collection: Collection<*>): Array<Any?>",
    )
    val randomAccessDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "public expect interface RandomAccess",
    )
    val typedCollectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun <T> collectionToArray(collection: Collection<*>, array: Array<T>): Array<T>",
    )
    val arrayOfNullsFromReferenceDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsHeaderFile,
        "internal expect fun <T> arrayOfNulls(reference: Array<T>, size: Int): Array<T>",
    )
    val collectionToArrayImplementation = extractCommonFunction(
        commonCollectionsFile,
        "internal fun collectionToArrayCommonImpl(collection: Collection<*>): Array<Any?>",
    )
    val typedCollectionToArrayImplementation = extractCommonFunction(
        commonCollectionsFile,
        "internal fun <T> collectionToArrayCommonImpl(collection: Collection<*>, array: Array<T>): Array<T>",
    )
    val terminateCollectionToArrayDeclaration = extractCommonSingleLineDeclaration(
        commonCollectionsFile,
        "internal expect fun <T> terminateCollectionToArray(collectionSize: Int, array: Array<T>): Array<T>",
    )
    val iterableSelectorSums = listOf("Double", "Int", "Long").map { selectorType ->
        Aggregates.f_sumOf().singleCommonTemplate(
            family = Family.Iterables,
            signature = "sumOf(selector: (T) -> $selectorType)",
        )
    }
    val iterableFlatMapIndexed = Mapping.f_flatMapIndexed.singleCommonTemplate(
        family = Family.Iterables,
        signature = "flatMapIndexed(transform: (index: Int, T) -> Iterable<R>)",
    )
    val iterableFlatMapIndexedTo = Mapping.f_flatMapIndexedTo.singleCommonTemplate(
        family = Family.Iterables,
        signature = "flatMapIndexedTo(destination: C, transform: (index: Int, T) -> Iterable<R>)",
    )
    val selectedTemplates = sequenceOf(
        Aggregates.f_all selectedFor setOf(Family.Iterables),
        Aggregates.f_any selectedFor setOf(Family.Iterables),
        Aggregates.f_any_predicate selectedFor setOf(Family.Iterables),
        Aggregates.f_count selectedFor setOf(Family.Iterables, Family.Collections),
        Aggregates.f_count_predicate selectedFor setOf(Family.Iterables),
        Aggregates.f_fold selectedFor setOf(Family.Iterables),
        Aggregates.f_foldIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_foldRight selectedFor setOf(Family.Lists),
        Aggregates.f_foldRightIndexed selectedFor setOf(Family.Lists),
        Aggregates.f_forEach selectedFor setOf(Family.Iterables),
        Aggregates.f_forEachIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_none selectedFor setOf(Family.Iterables),
        Aggregates.f_none_predicate selectedFor setOf(Family.Iterables),
        Aggregates.f_onEach selectedFor setOf(Family.Iterables),
        Aggregates.f_onEachIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceIndexedSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceIndexedOrNullSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceOrNullSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_reduceRightSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightIndexedSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightIndexedOrNullSuper selectedFor setOf(Family.Lists),
        Aggregates.f_reduceRightOrNullSuper selectedFor setOf(Family.Lists),
        Aggregates.f_runningFold selectedFor setOf(Family.Iterables),
        Aggregates.f_runningFoldIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_runningReduceSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_runningReduceIndexedSuper selectedFor setOf(Family.Iterables),
        Aggregates.f_scan selectedFor setOf(Family.Iterables),
        Aggregates.f_scanIndexed selectedFor setOf(Family.Iterables),
        Aggregates.f_sumBy selectedFor setOf(Family.Iterables),
        Aggregates.f_sumByDouble selectedFor setOf(Family.Iterables),
        ArrayOps.f_isEmpty selectedFor setOf(Family.ArraysOfObjects),
        ArrayOps.f_isNotEmpty selectedFor setOf(Family.ArraysOfObjects),
        Elements.f_contains selectedFor setOf(Family.Iterables),
        Elements.f_contains selectedFor setOf(Family.ArraysOfObjects),
        Elements.f_elementAt selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_elementAtOrElse selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_elementAtOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_find selectedFor setOf(Family.Iterables),
        Elements.f_findLast selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_first selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_firstNotNullOf selectedFor setOf(Family.Iterables),
        Elements.f_firstNotNullOfOrNull selectedFor setOf(Family.Iterables),
        Elements.f_first_predicate selectedFor setOf(Family.Iterables),
        Elements.f_firstOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_firstOrNull_predicate selectedFor setOf(Family.Iterables),
        Elements.f_getOrElse selectedFor setOf(Family.Lists),
        Elements.f_getOrNull selectedFor setOf(Family.Lists, Family.ArraysOfObjects),
        Elements.f_indexOf selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_indexOf selectedFor setOf(Family.ArraysOfObjects),
        Elements.f_indexOfFirst selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_indexOfLast selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_last selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_last_predicate selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastIndexOf selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_lastOrNull_predicate selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_single selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_single_predicate selectedFor setOf(Family.Iterables),
        Elements.f_singleOrNull selectedFor setOf(Family.Iterables, Family.Lists),
        Elements.f_singleOrNull_predicate selectedFor setOf(Family.Iterables),
        Filtering.f_drop selectedFor setOf(Family.Iterables),
        Filtering.f_dropLast selectedFor setOf(Family.Lists),
        Filtering.f_dropLastWhile selectedFor setOf(Family.Lists),
        Filtering.f_dropWhile selectedFor setOf(Family.Iterables),
        Filtering.f_filter selectedFor setOf(Family.Iterables),
        Filtering.f_filterIndexed selectedFor setOf(Family.Iterables),
        Filtering.f_filterIndexedTo selectedFor setOf(Family.Iterables),
        Filtering.f_filterNot selectedFor setOf(Family.Iterables),
        Filtering.f_filterNotNull selectedFor setOf(Family.Iterables),
        Filtering.f_filterNotNullTo selectedFor setOf(Family.Iterables),
        Filtering.f_filterNotTo selectedFor setOf(Family.Iterables),
        Filtering.f_filterTo selectedFor setOf(Family.Iterables),
        Filtering.f_slice selectedFor setOf(Family.Lists),
        Filtering.f_take selectedFor setOf(Family.Iterables),
        Filtering.f_takeLast selectedFor setOf(Family.Lists),
        Filtering.f_takeLastWhile selectedFor setOf(Family.Lists),
        Filtering.f_takeWhile selectedFor setOf(Family.Iterables),
        Generators.f_minus selectedFor setOf(Family.Iterables),
        Generators.f_minus_array selectedFor setOf(Family.Iterables),
        Generators.f_minus_iterable selectedFor setOf(Family.Iterables),
        Generators.f_minusElement selectedFor setOf(Family.Iterables),
        Generators.f_partition selectedFor setOf(Family.Iterables),
        Generators.f_plus selectedFor setOf(Family.Iterables, Family.Collections),
        Generators.f_plus_array selectedFor setOf(Family.Iterables, Family.Collections),
        Generators.f_plus_iterable selectedFor setOf(Family.Iterables, Family.Collections),
        Generators.f_plusElement selectedFor setOf(Family.Iterables, Family.Collections),
        Generators.f_zip selectedFor setOf(Family.Iterables),
        Generators.f_zip_array selectedFor setOf(Family.Iterables),
        Generators.f_zip_array_transform selectedFor setOf(Family.Iterables),
        Generators.f_zip_transform selectedFor setOf(Family.Iterables),
        Generators.f_zipWithNext selectedFor setOf(Family.Iterables),
        Generators.f_zipWithNext_transform selectedFor setOf(Family.Iterables),
        Guards.f_requireNoNulls selectedFor setOf(Family.Iterables, Family.Lists),
        Mapping.f_flatMap selectedFor setOf(Family.Iterables),
        iterableFlatMapIndexed selectedFor setOf(Family.Iterables),
        iterableFlatMapIndexedTo selectedFor setOf(Family.Iterables),
        Mapping.f_flatMapTo selectedFor setOf(Family.Iterables),
        Mapping.f_map selectedFor setOf(Family.Iterables),
        Mapping.f_mapIndexed selectedFor setOf(Family.Iterables),
        Mapping.f_mapIndexedNotNull selectedFor setOf(Family.Iterables),
        Mapping.f_mapIndexedNotNullTo selectedFor setOf(Family.Iterables),
        Mapping.f_mapIndexedTo selectedFor setOf(Family.Iterables),
        Mapping.f_mapNotNull selectedFor setOf(Family.Iterables),
        Mapping.f_mapNotNullTo selectedFor setOf(Family.Iterables),
        Mapping.f_mapTo selectedFor setOf(Family.Iterables),
        Mapping.f_withIndex selectedFor setOf(Family.Iterables),
        (Numeric.f_average selectedFor setOf(Family.Iterables))
            .limitedTo(PrimitiveType.numericPrimitives),
        (Numeric.f_sum selectedFor setOf(Family.Iterables))
            .limitedTo(PrimitiveType.numericPrimitives),
        Ordering.f_reverse selectedFor setOf(Family.Lists),
        Ordering.f_reversed selectedFor setOf(Family.Iterables),
        SequenceOps.f_asIterable selectedFor setOf(Family.Iterables),
        Snapshots.f_toCollection selectedFor setOf(Family.Iterables),
        Snapshots.f_toList selectedFor setOf(Family.Iterables),
        Snapshots.f_toMutableList selectedFor setOf(Family.Iterables, Family.Collections),
        (ArrayOps.f_toPrimitiveArray selectedFor setOf(Family.Collections))
            .limitedTo(PrimitiveType.defaultPrimitives),
        StringJoinOps.f_joinTo selectedFor setOf(Family.Iterables),
        StringJoinOps.f_joinToString selectedFor setOf(Family.Iterables),
    ) + iterableSelectorSums.asSequence().map { selectorSum ->
        selectorSum selectedFor setOf(Family.Iterables)
    } + Elements.f_components.asSequence().map { component ->
        component selectedFor setOf(Family.Lists)
    }
    val members = selectedTemplates
        .flatMap { selection ->
            selection.template.instantiate(listOf(KotlinTarget.Common)).filter { member ->
                member.family in selection.families &&
                        (selection.primitives == null || member.primitive in selection.primitives)
            }
        }
        .sortedBy { it.sortingSignature }
        .toList()

    val generatedSource = StringWriter()
    generatedSource.appendLine(COPYRIGHT_NOTICE)
    generatedSource.appendLine("package kotlin.collections")
    generatedSource.appendLine()
    generatedSource.appendLine("import kotlin.contracts.*")
    generatedSource.appendLine()
    generatedSource.appendLine(autoGeneratedWarning("GenerateDotNetBootstrapCollections.kt"))
    generatedSource.appendLine(arrayAsListDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(lastIndexDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(randomAccessDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(checkIndexOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(checkCountOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(throwIndexOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(throwCountOverflowDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(collectionToArrayDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(typedCollectionToArrayDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(arrayOfNullsFromReferenceDeclaration)
    generatedSource.appendLine()
    generatedSource.appendLine(collectionToArrayImplementation)
    generatedSource.appendLine()
    generatedSource.appendLine(typedCollectionToArrayImplementation)
    generatedSource.appendLine()
    generatedSource.appendLine(terminateCollectionToArrayDeclaration)
    generatedSource.appendLine()
    for (member in members) {
        member.build(generatedSource)
    }
    generatedSource.appendLine(
        """
        /**
         * Private resolution marker for the exact Common `Array.getOrNull` body above.
         *
         * The shared range-contains lowering consumes every call before CIL generation. This is
         * intentionally not a public `Array.indices` product: publishing that property requires
         * the complete `IntRange` dependency closure, which is outside this bootstrap slice.
         */
        private val <T> Array<out T>.indices: IntRange
            get() = throw AssertionError("Array.indices bootstrap marker survived lowering")
        """.trimIndent()
    )
    generatedSource.appendLine()
    generatedSource.appendLine(
        """
        /**
         * Private resolution marker for end-exclusive counted loops in the exact Common bodies.
         *
         * [DotNetForLoopLowering] consumes every call before CIL generation. Publishing the real
         * function would publish `IntRange`, whose product remains outside this bootstrap batch.
         */
        private infix fun Int.until(to: Int): IntRange =
            throw AssertionError("Int.until bootstrap marker survived lowering: ${'$'}this until ${'$'}to")
        """.trimIndent()
    )
    val normalizedSource = generatedSource.toString()
        .replace("\r\n", "\n")
        .lineSequence()
        .joinToString("\n") { line -> line.trimEnd() }
        .trimEnd() + "\n"
    outputFile.parentFile.mkdirs()
    outputFile.writeText(normalizedSource, Charsets.UTF_8)

    appendableOutputFile.writeText(
        projectWholeCommonFile(commonAppendableFile),
        Charsets.UTF_8,
    )
    stringBuilderOutputFile.writeText(
        projectWholeCommonFile(commonStringBuilderFile),
        Charsets.UTF_8,
    )
    kotlinOutputFile.writeText(
        projectStandardFile(commonStandardFile),
        Charsets.UTF_8,
    )
    enumEntriesOutputFile.writeText(
        projectEnumEntriesFile(commonEnumEntriesFile),
        Charsets.UTF_8,
    )
    enumOutputFile.writeText(
        projectEnumFile(commonEnumFile),
        Charsets.UTF_8,
    )
    jsNameOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin.js",
            imports = listOf(
                "kotlin.annotation.AnnotationTarget.*",
                "kotlin.internal.UsedFromCompilerGeneratedCode",
            ),
            declarations = listOf(
                extractCommonDeclaration(
                    commonJsAnnotationsFile,
                    "public expect annotation class JsName(val name: String)",
                ),
                extractCommonDeclaration(
                    commonJsAnnotationsFile,
                    "internal annotation class JsImplicitExport(val couldBeConvertedToExplicitExport: Boolean)",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
    experimentalTypeInferenceOutputFile.writeText(
        projectWholeCommonFile(commonExperimentalTypeInferenceFile),
        Charsets.UTF_8,
    )
    overloadResolutionByLambdaReturnTypeOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin",
            imports = listOf(
                "kotlin.annotation.AnnotationTarget.*",
                "kotlin.experimental.ExperimentalTypeInference",
            ),
            declarations = listOf(
                extractFinalCommonDeclaration(
                    commonInferenceAnnotationsFile,
                    "public annotation class OverloadResolutionByLambdaReturnType",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
    mutableCollectionsOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin.collections",
            declarations = listOf(
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline fun <@kotlin.internal.OnlyInputTypes T> MutableCollection<out T>.remove(element: T)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline fun <@kotlin.internal.OnlyInputTypes T> MutableCollection<out T>.removeAll(elements: Collection<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline fun <@kotlin.internal.OnlyInputTypes T> MutableCollection<out T>.retainAll(elements: Collection<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline operator fun <T> MutableCollection<in T>.plusAssign(element: T)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline operator fun <T> MutableCollection<in T>.plusAssign(elements: Iterable<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline operator fun <T> MutableCollection<in T>.plusAssign(elements: Array<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline operator fun <T> MutableCollection<in T>.minusAssign(element: T)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline operator fun <T> MutableCollection<in T>.minusAssign(elements: Iterable<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline operator fun <T> MutableCollection<in T>.minusAssign(elements: Array<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableCollection<in T>.addAll(elements: Iterable<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableCollection<in T>.addAll(elements: Array<out T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "internal fun <T> Iterable<T>.convertToListIfNotCollection(): Collection<T>",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableCollection<in T>.removeAll(elements: Iterable<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableCollection<in T>.removeAll(elements: Array<out T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableCollection<in T>.retainAll(elements: Iterable<T>)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableCollection<in T>.retainAll(elements: Array<out T>)",
                ),
                extractCommonFunction(
                    commonMutableCollectionsFile,
                    "private fun MutableCollection<*>.retainNothing(): Boolean",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableIterable<T>.removeAll(predicate: (T) -> Boolean)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableIterable<T>.retainAll(predicate: (T) -> Boolean)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public inline fun <T> MutableList<T>.remove(index: Int)",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableList<T>.removeFirst(): T",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableList<T>.removeFirstOrNull(): T?",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableList<T>.removeLast(): T",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableList<T>.removeLastOrNull(): T?",
                ),
                extractCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableList<T>.removeAll(predicate: (T) -> Boolean)",
                ),
                extractFinalCommonDeclaration(
                    commonMutableCollectionsFile,
                    "public fun <T> MutableList<T>.retainAll(predicate: (T) -> Boolean)",
                ),
                """
                /** Private resolution marker consumed by the .NET counted-loop lowering. */
                private infix fun Int.downTo(to: Int): IntProgression =
                    throw AssertionError("Int.downTo bootstrap marker survived lowering: ${'$'}this downTo ${'$'}to")
                """.trimIndent(),
            ),
        ),
        Charsets.UTF_8,
    )
    preconditionsOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin",
            imports = listOf("kotlin.contracts.contract"),
            declarations = listOf(
                extractCommonDeclaration(
                    commonPreconditionsFile,
                    "public inline fun require(value: Boolean): Unit",
                ),
                extractCommonDeclaration(
                    commonPreconditionsFile,
                    "public inline fun require(value: Boolean, lazyMessage: () -> Any): Unit",
                ),
                extractCommonDeclaration(
                    commonPreconditionsFile,
                    "public inline fun check(value: Boolean): Unit",
                ),
                extractCommonDeclaration(
                    commonPreconditionsFile,
                    "public inline fun check(value: Boolean, lazyMessage: () -> Any): Unit",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
    collectionFactoriesOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin.collections",
            imports = listOf("kotlin.contracts.*"),
            declarations = listOf(
                extractCommonSourceRange(
                    commonCollectionsFile,
                    startMarker = "internal object EmptyIterator : ListIterator<Nothing>",
                    endMarker = "@kotlin.internal.InlineOnly\ninternal expect inline fun <T> Array<out T>.asArrayList(): ArrayList<T>",
                ),
                extractCommonUndocumentedDeclaration(
                    commonCollectionsFile,
                    "internal expect inline fun <T> Array<out T>.asArrayList(): ArrayList<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public fun <T> emptyList(): List<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public fun <T> listOf(vararg elements: T): List<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public expect fun <T> listOf(element: T): List<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <T> listOf(): List<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <T> mutableListOf(): MutableList<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <T> arrayListOf(): ArrayList<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public fun <T> mutableListOf(vararg elements: T): MutableList<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public fun <T> arrayListOf(vararg elements: T): ArrayList<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public fun <T : Any> listOfNotNull(element: T?): List<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <E> buildList(builderAction: MutableList<E>.() -> Unit): List<E>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <E> buildList(capacity: Int, builderAction: MutableList<E>.() -> Unit): List<E>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <T> Collection<T>.isNotEmpty(): Boolean",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <T> Collection<T>?.isNullOrEmpty(): Boolean",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <T> Collection<T>?.orEmpty(): Collection<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <T> List<T>?.orEmpty(): List<T>",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <C, R> C.ifEmpty(defaultValue: () -> R): R where C : Collection<*>, C : R",
                ),
                extractCommonDeclaration(
                    commonCollectionsFile,
                    "public inline fun <@kotlin.internal.OnlyInputTypes T> Collection<T>.containsAll(elements: Collection<T>): Boolean",
                ),
                extractCommonUndocumentedDeclaration(
                    commonCollectionsFile,
                    "internal fun <T> List<T>.optimizeReadOnlyList()",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
    outOfMemoryErrorOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin",
            declarations = listOf(
                extractCommonFunction(
                    commonOutOfMemoryErrorFile,
                    "public expect open class OutOfMemoryError : Error",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
    scalarBoundsOutputFile.writeText(
        buildProjectedSource(
            packageName = "kotlin",
            declarations = listOf(
                extractCommonDeclaration(
                    commonComparisonsFile,
                    "public expect inline fun minOf(a: Int, b: Int): Int",
                ),
                extractCommonDeclaration(
                    commonRangesFile,
                    "public fun Int.coerceAtLeast(minimumValue: Int): Int",
                ),
            ),
        ),
        Charsets.UTF_8,
    )
}

private fun projectEnumFile(sourceFile: File): String {
    var projectedSource = sourceFile.readText().replace("\r\n", "\n")
    val commonConstructor =
        "public expect abstract class Enum<E : Enum<E>>(name: String, ordinal: Int): Comparable<E> {"
    val bootstrapConstructor =
        "public expect abstract class Enum<E : Enum<E>>(name: String = \"\", ordinal: Int = -1): Comparable<E> {"
    check(projectedSource.countOccurrences(commonConstructor) == 1) {
        "Expected exactly one Common Enum constructor in ${sourceFile.path}"
    }
    // A serialized Enum constructor is deserialized by FIR with synthetic defaults regardless
    // of its proto flags. The temporary same-compilation source product has no deserialization
    // boundary, so express those two frontend-only placeholders in source. The enum lowering
    // always replaces them with the exact entry name and ordinal; no physical default stub may
    // survive. Remove this projection when the stdlib is always consumed as an installed KLIB.
    projectedSource = projectedSource.replace(commonConstructor, bootstrapConstructor)
    return injectGeneratedWarning(projectedSource)
}

private fun projectEnumEntriesFile(sourceFile: File): String {
    var projectedSource = sourceFile.readText().replace("\r\n", "\n")
    val commonFileSuppression =
        "@file:Suppress(\"EXPECT_AND_ACTUAL_IN_THE_SAME_MODULE\") // for building kotlin-stdlib-jvm-minimal-for-test"
    check(projectedSource.countOccurrences(commonFileSuppression) == 1) {
        "Expected exactly one Common EnumEntries file suppression in ${sourceFile.path}"
    }
    // This suppression belongs to the JVM minimal-test source layout. The .NET common/platform
    // split has no same-module expect/actual declaration and its test harness correctly rejects
    // suppressing an error diagnostic in injected bootstrap source.
    projectedSource = projectedSource.replace(commonFileSuppression, "")
    val reifiedSurface = extractCommonDeclarationPrefix(
        sourceFile,
        "public inline fun <reified T : Enum<T>> enumEntries(): EnumEntries<T>",
        "@PublishedApi\n@SinceKotlin(\"1.8\") // Used by pre-1.9.0 JVM compiler for the feature in preview mode.",
    )
    check(projectedSource.countOccurrences(reifiedSurface) == 1) {
        "Expected exactly one reified enum-entries surface in ${sourceFile.path}"
    }
    projectedSource = projectedSource.replace(reifiedSurface, "")
    return injectGeneratedWarning(projectedSource)
}

/**
 * Copies a documented declaration plus its immediately following declarations up to one exact
 * retained declaration prefix. This is used for Common source tails where the ordinary next-KDoc
 * boundary does not exist; both markers stay fail-closed under upstream regrouping.
 */
private fun extractCommonDeclarationPrefix(
    sourceFile: File,
    declarationHeader: String,
    retainedDeclarationPrefix: String,
): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val documentationIndex = source.lastIndexOf("/**", declarationIndex)
    check(documentationIndex >= 0) {
        "Cannot find KDoc for Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val retainedDeclarationIndex = source.indexOf(retainedDeclarationPrefix, declarationIndex)
    check(retainedDeclarationIndex >= 0) {
        "Cannot find retained Common declaration prefix '$retainedDeclarationPrefix' in ${sourceFile.path}"
    }
    check(source.indexOf(retainedDeclarationPrefix, retainedDeclarationIndex + retainedDeclarationPrefix.length) < 0) {
        "Retained Common declaration prefix '$retainedDeclarationPrefix' is not unique in ${sourceFile.path}"
    }
    return source.substring(documentationIndex, retainedDeclarationIndex).trimEnd()
}

internal fun projectWholeCommonFile(
    sourceFile: File,
    generatorName: String = "GenerateDotNetBootstrapCollections.kt",
): String {
    val normalizedSource = sourceFile.readText().replace("\r\n", "\n")
    return injectGeneratedWarning(normalizedSource, generatorName)
}

/**
 * Retains the complete contract-bearing scope-function closure while `repeat` remains behind the
 * ordinary range/progression product. The declaration is the exact final Common source tail, so
 * upstream movement or added declarations after it fail generation instead of silently widening
 * this temporary projection.
 */
private fun projectStandardFile(sourceFile: File): String {
    var projectedSource = sourceFile.readText().replace("\r\n", "\n")
    val declarationHeader = "public inline fun repeat(times: Int, action: (Int) -> Unit)"
    val declarationIndex = projectedSource.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(projectedSource.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val documentationIndex = projectedSource.lastIndexOf("/**", declarationIndex)
    check(documentationIndex >= 0) {
        "Cannot find KDoc for Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val declaration = extractCommonFunction(sourceFile, declarationHeader)
    val declarationEnd = declarationIndex + declaration.length
    check(projectedSource.substring(declarationEnd).isBlank()) {
        "Common repeat is no longer the final declaration in ${sourceFile.path}"
    }
    projectedSource = projectedSource.substring(0, documentationIndex)
    return injectGeneratedWarning(projectedSource)
}

private fun injectGeneratedWarning(
    source: String,
    generatorName: String = "GenerateDotNetBootstrapCollections.kt",
): String {
    val packageMarker = "package "
    val packageIndex = source.indexOf(packageMarker)
    check(packageIndex >= 0) { "Projected Common source has no package declaration" }
    val packageLineEnd = source.indexOf('\n', packageIndex)
    check(packageLineEnd >= 0) { "Projected Common source has an unterminated package declaration" }
    val warning = autoGeneratedWarning(generatorName).trimEnd()
    return (source.substring(0, packageLineEnd + 1) + "\n" + warning + "\n" + source.substring(packageLineEnd + 1))
        .lineSequence()
        .joinToString("\n") { line -> line.trimEnd() }
        .trimEnd() + "\n"
}

internal fun buildProjectedSource(
    packageName: String,
    fileAnnotations: List<String> = emptyList(),
    imports: List<String> = emptyList(),
    declarations: List<String>,
    generatorName: String = "GenerateDotNetBootstrapCollections.kt",
): String = buildString {
    appendLine(COPYRIGHT_NOTICE)
    for (annotation in fileAnnotations) appendLine("@file:$annotation")
    if (fileAnnotations.isNotEmpty()) appendLine()
    appendLine("package $packageName")
    appendLine()
    appendLine(autoGeneratedWarning(generatorName))
    for (importName in imports) appendLine("import $importName")
    if (imports.isNotEmpty()) appendLine()
    append(declarations.joinToString("\n\n"))
    appendLine()
}.lineSequence()
    .joinToString("\n") { line -> line.trimEnd() }
    .trimEnd() + "\n"

private fun String.countOccurrences(needle: String): Int {
    check(needle.isNotEmpty())
    var count = 0
    var fromIndex = 0
    while (true) {
        val index = indexOf(needle, fromIndex)
        if (index < 0) return count
        count++
        fromIndex = index + needle.length
    }
}

/** Copies one exact source interval and fails when either ownership marker ceases to be unique. */
private fun extractCommonSourceRange(sourceFile: File, startMarker: String, endMarker: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    check(source.countOccurrences(startMarker) == 1) {
        "Expected one Common range start '$startMarker' in ${sourceFile.path}"
    }
    check(source.countOccurrences(endMarker) == 1) {
        "Expected one Common range end '$endMarker' in ${sourceFile.path}"
    }
    val startIndex = source.indexOf(startMarker)
    val endIndex = source.indexOf(endMarker, startIndex + startMarker.length)
    check(endIndex > startIndex) {
        "Common range end '$endMarker' does not follow '$startMarker' in ${sourceFile.path}"
    }
    return source.substring(startIndex, endIndex).trimEnd()
}

private data class SelectedTemplate(
    val template: MemberTemplate,
    val families: Set<Family>,
    val primitives: Set<PrimitiveType>? = null,
)

private infix fun MemberTemplate.selectedFor(families: Set<Family>): SelectedTemplate =
    SelectedTemplate(this, families)

private fun SelectedTemplate.limitedTo(primitives: Set<PrimitiveType>): SelectedTemplate =
    copy(primitives = primitives)

/** Selects one overload template by its exact authoritative Common family/signature pair. */
private fun List<MemberTemplate>.singleCommonTemplate(
    family: Family,
    signature: String,
): MemberTemplate {
    val matches = filter { template ->
        template.instantiate(listOf(KotlinTarget.Common)).any { member ->
            member.family == family && member.signature == signature
        }
    }
    check(matches.size == 1) {
        "Expected one Common $family template '$signature', found ${matches.size}"
    }
    return matches.single()
}

/**
 * Copies one complete declaration from an authoritative Common source file. The unique declaration
 * header is deliberately a hard generation contract: upstream movement or signature changes fail
 * instead of leaving the bootstrap projection silently stale.
 */
internal fun extractCommonDeclaration(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val documentationIndex = source.lastIndexOf("/**", declarationIndex)
    check(documentationIndex >= 0) {
        "Cannot find KDoc for Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val nextDocumentationIndex = source.indexOf("\n/**", declarationIndex)
    check(nextDocumentationIndex >= 0) {
        "Cannot find the end of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    return source.substring(documentationIndex, nextDocumentationIndex).trimEnd()
}

/**
 * Copies one documented declaration that is authoritatively the final declaration in its Common
 * source file. Both the unique header and empty trailing source fail closed under regrouping.
 */
private fun extractFinalCommonDeclaration(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find final Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Final Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val documentationIndex = source.lastIndexOf("/**", declarationIndex)
    check(documentationIndex >= 0) {
        "Cannot find KDoc for final Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf("\n/**", declarationIndex) < 0) {
        "Common declaration '$declarationHeader' is no longer final in ${sourceFile.path}"
    }
    return source.substring(documentationIndex).trimEnd()
}

/**
 * Copies one annotation-led declaration that intentionally has no KDoc. Blank declaration
 * boundaries are part of the fail-closed contract, so an upstream regrouping requires review.
 */
internal fun extractCommonUndocumentedDeclaration(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common declaration header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val declarationStart = source.lastIndexOf("\n\n", declarationIndex)
    check(declarationStart >= 0) {
        "Cannot find the start of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    val declarationEnd = source.indexOf("\n\n", declarationIndex)
    check(declarationEnd >= 0) {
        "Cannot find the end of Common declaration '$declarationHeader' in ${sourceFile.path}"
    }
    return source.substring(declarationStart + 2, declarationEnd).trimEnd()
}

/** Copies one complete single-line declaration and rejects any unexpected trailing source. */
internal fun extractCommonSingleLineDeclaration(sourceFile: File, declaration: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declaration)
    check(declarationIndex >= 0) {
        "Cannot find Common declaration '$declaration' in ${sourceFile.path}"
    }
    check(source.indexOf(declaration, declarationIndex + declaration.length) < 0) {
        "Common declaration '$declaration' is not unique in ${sourceFile.path}"
    }
    val lineStart = source.lastIndexOf('\n', declarationIndex - 1) + 1
    val lineEnd = source.indexOf('\n', declarationIndex).takeIf { it >= 0 } ?: source.length
    check(source.substring(lineStart, lineEnd) == declaration) {
        "Common declaration '$declaration' is no longer one complete line in ${sourceFile.path}"
    }
    return declaration
}

/**
 * Copies one complete block-bodied function from authoritative Common source. The unique header
 * and balanced body are fail-closed generation contracts; the .NET source product does not own a
 * second spelling of the algorithm.
 */
private fun extractCommonFunction(sourceFile: File, declarationHeader: String): String {
    val source = sourceFile.readText().replace("\r\n", "\n")
    val declarationIndex = source.indexOf(declarationHeader)
    check(declarationIndex >= 0) {
        "Cannot find Common function '$declarationHeader' in ${sourceFile.path}"
    }
    check(source.indexOf(declarationHeader, declarationIndex + declarationHeader.length) < 0) {
        "Common function header '$declarationHeader' is not unique in ${sourceFile.path}"
    }
    val bodyStart = source.indexOf('{', declarationIndex + declarationHeader.length)
    check(bodyStart >= 0) {
        "Cannot find Common function body for '$declarationHeader' in ${sourceFile.path}"
    }
    var depth = 0
    for (index in bodyStart until source.length) {
        when (source[index]) {
            '{' -> depth++
            '}' -> {
                depth--
                check(depth >= 0) {
                    "Unbalanced Common function body for '$declarationHeader' in ${sourceFile.path}"
                }
                if (depth == 0) {
                    return source.substring(declarationIndex, index + 1).trimEnd()
                }
            }
        }
    }
    error("Unterminated Common function body for '$declarationHeader' in ${sourceFile.path}")
}
