/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Kotlin.DotNet.CSharpAuthoring.Manifest;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Kotlin.DotNet.CSharpAuthoring;

/// <summary>
/// Generates the CLR-physical interface implementation surface for a user-authored partial C#
/// type whose real base list names a Kotlin interface.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class KotlinInterfaceImplementationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (productionContext, compilation) =>
            {
                KotlinManifestSet manifests = ManifestReader.Read(compilation);
                if (!manifests.Problems.IsEmpty)
                    return;
                System.Collections.Immutable.ImmutableArray<Diagnostic>
                    compilerErrors = DiagnosticOwnership.CompilerErrors(
                        compilation,
                        productionContext.CancellationToken);
                foreach (AuthoringContract contract in AuthoringContractDiscovery.Discover(
                             compilation,
                             manifests,
                             diagnostic =>
                             {
                                 if (DiagnosticOwnership.HasBlockingCompilerError(
                                         diagnostic.Location,
                                         compilerErrors,
                                         productionContext.CancellationToken))
                                     productionContext.ReportDiagnostic(diagnostic);
                             }))
                {
                    KotlinImplementationEmission emission =
                        KotlinImplementationEmitter.Emit(contract);
                    foreach (Diagnostic diagnostic in emission.Diagnostics)
                    {
                        if (DiagnosticOwnership.HasBlockingCompilerError(
                                diagnostic.Location,
                                compilerErrors,
                                productionContext.CancellationToken))
                            productionContext.ReportDiagnostic(diagnostic);
                    }
                    if (emission.HasErrors)
                        continue;
                    string source = EmitContractMarker(
                        contract,
                        emission.GeneratedMembers,
                        emission.AdditionalInterfaces);
                    productionContext.AddSource(
                        HintName(contract.ImplementationType) + ".KotlinInterfaceImplementation.g.cs",
                        SourceText.From(source, Encoding.UTF8));
                }
            });
    }

    private static string EmitContractMarker(
        AuthoringContract contract,
        string generatedMembers,
        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol> additionalInterfaces)
    {
        INamedTypeSymbol type = contract.ImplementationType;
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ");
            source.Append(type.ContainingNamespace.ToDisplayString());
            source.AppendLine();
            source.AppendLine("{");
        }

        string indent = type.ContainingNamespace.IsGlobalNamespace ? "" : "    ";
        var typeChain = new Stack<INamedTypeSymbol>();
        INamedTypeSymbol? current = type;
        while (current != null)
        {
            typeChain.Push(current);
            current = current.ContainingType;
        }
        foreach (INamedTypeSymbol declarationType in typeChain)
        {
            source.Append(indent);
            AppendTypeDeclaration(
                source,
                declarationType,
                SymbolEqualityComparer.Default.Equals(declarationType, type)
                    ? additionalInterfaces
                    : default);
            source.AppendLine();
            source.Append(indent);
            source.AppendLine("{");
            indent += "    ";
        }
        if (generatedMembers.Length != 0)
        {
            foreach (string line in generatedMembers.Split('\n'))
            {
                if (line.Length != 0)
                    source.Append(indent);
                source.AppendLine(line.TrimEnd('\r'));
            }
        }
        for (int index = 0; index < typeChain.Count; index++)
        {
            indent = indent.Substring(0, indent.Length - 4);
            source.Append(indent);
            source.AppendLine("}");
        }
        if (!type.ContainingNamespace.IsGlobalNamespace)
            source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendTypeDeclaration(
        StringBuilder source,
        INamedTypeSymbol type,
        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol> additionalInterfaces)
    {
        if (type.IsStatic)
            source.Append("static ");
        if (type.TypeKind == TypeKind.Struct)
        {
            if (type.IsReadOnly)
                source.Append("readonly ");
            if (type.IsRefLikeType)
                source.Append("ref ");
        }
        source.Append("partial ");
        if (type.IsRecord)
        {
            source.Append(type.TypeKind == TypeKind.Struct
                ? "record struct "
                : "record class ");
        }
        else
        {
            switch (type.TypeKind)
            {
                case TypeKind.Class:
                    source.Append("class ");
                    break;
                case TypeKind.Struct:
                    source.Append("struct ");
                    break;
                case TypeKind.Interface:
                    source.Append("interface ");
                    break;
                default:
                    throw new InvalidOperationException(
                        "Unsupported partial containing type " +
                        type.ToDisplayString());
            }
        }
        source.Append(EscapeIdentifier(type.Name));
        if (type.TypeParameters.Length != 0)
        {
            source.Append('<');
            source.Append(string.Join(
                ", ",
                type.TypeParameters.Select(parameter =>
                    TypeParameterDeclaration(type, parameter))));
            source.Append('>');
        }
        if (!additionalInterfaces.IsDefaultOrEmpty)
        {
            source.Append(" : ");
            source.Append(string.Join(
                ", ",
                additionalInterfaces.Select(interfaceType =>
                    interfaceType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat))));
        }
    }

    private static string TypeParameterDeclaration(
        INamedTypeSymbol owner,
        ITypeParameterSymbol parameter)
    {
        string variance = owner.TypeKind == TypeKind.Interface
            ? parameter.Variance == VarianceKind.In
                ? "in "
                : parameter.Variance == VarianceKind.Out
                    ? "out "
                    : ""
            : "";
        return variance + EscapeIdentifier(parameter.Name);
    }

    private static string HintName(INamedTypeSymbol type)
    {
        byte[] identity = Encoding.UTF8.GetBytes(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        byte[] digest;
        using (SHA256 algorithm = SHA256.Create())
            digest = algorithm.ComputeHash(identity);
        var result = new StringBuilder(digest.Length * 2);
        foreach (byte value in digest)
            result.Append(value.ToString("x2", CultureInfo.InvariantCulture));
        return result.ToString();
    }

    private static string EscapeIdentifier(string name)
    {
        return Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name) ==
               Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
            ? name
            : "@" + name;
    }
}
