/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

using System;
using System.Linq;
using System.Text;
using Kotlin.DotNet.CSharpAuthoring.Manifest;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Kotlin.DotNet.CSharpAuthoring;

/// <summary>
/// Generates the CLR-physical interface implementation surface for a user-authored partial C#
/// type whose real base list names a Kotlin interface.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class KotlinInterfaceImplementationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (productionContext, compilation) =>
            {
                KotlinManifestSet manifests = ManifestReader.Read(compilation);
                if (!manifests.Problems.IsEmpty)
                    return;
                foreach (AuthoringContract contract in AuthoringContractDiscovery.Discover(
                             compilation,
                             manifests,
                             productionContext.ReportDiagnostic))
                {
                    KotlinImplementationEmission emission =
                        KotlinImplementationEmitter.Emit(contract);
                    foreach (Diagnostic diagnostic in emission.Diagnostics)
                        productionContext.ReportDiagnostic(diagnostic);
                    if (emission.HasErrors)
                        continue;
                    string source = EmitContractMarker(
                        contract,
                        emission.GeneratedMembers,
                        emission.AdditionalInterfaces);
                    productionContext.AddSource(
                        HintName(contract.ImplementationType) + ".KotlinInterfaceImplementation.g.cs",
                        SourceText.From(source, Encoding.UTF8));
                }
            });
    }

    private static string EmitContractMarker(
        AuthoringContract contract,
        string generatedMembers,
        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol> additionalInterfaces)
    {
        INamedTypeSymbol type = contract.ImplementationType;
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ");
            source.Append(type.ContainingNamespace.ToDisplayString());
            source.AppendLine();
            source.AppendLine("{");
        }

        string indent = type.ContainingNamespace.IsGlobalNamespace ? "" : "    ";
        source.Append(indent);
        source.Append("partial ");
        source.Append(type.IsRecord ? "record class " : "class ");
        source.Append(EscapeIdentifier(type.Name));
        if (type.TypeParameters.Length != 0)
        {
            source.Append('<');
            source.Append(string.Join(
                ", ",
                type.TypeParameters.Select(parameter => EscapeIdentifier(parameter.Name))));
            source.Append('>');
        }
        if (!additionalInterfaces.IsEmpty)
        {
            source.Append(" : ");
            source.Append(string.Join(
                ", ",
                additionalInterfaces.Select(interfaceType =>
                    interfaceType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat))));
        }
        source.AppendLine();
        source.Append(indent);
        source.AppendLine("{");
        if (generatedMembers.Length != 0)
        {
            foreach (string line in generatedMembers.Split('\n'))
            {
                if (line.Length != 0)
                    source.Append(indent);
                source.AppendLine(line.TrimEnd('\r'));
            }
        }
        source.Append(indent);
        source.AppendLine("}");
        if (!type.ContainingNamespace.IsGlobalNamespace)
            source.AppendLine("}");
        return source.ToString();
    }

    private static string HintName(INamedTypeSymbol type)
    {
        var result = new StringBuilder();
        foreach (char character in type.ToDisplayString())
            result.Append(char.IsLetterOrDigit(character) ? character : '_');
        return result.ToString();
    }

    private static string EscapeIdentifier(string name)
    {
        return Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name) ==
               Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
            ? name
            : "@" + name;
    }
}
