// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "Deprecation_Error", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

@kotlin.OptIn(org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi::class)
internal object KotlinDotNetCompilerOptionsHelper {

    internal fun fillCompilerArguments(
        from: org.jetbrains.kotlin.gradle.dsl.KotlinDotNetCompilerOptions,
        args: org.jetbrains.kotlin.cli.common.arguments.K2DotNetCompilerArguments,
    ) {
        org.jetbrains.kotlin.gradle.dsl.KotlinCommonCompilerOptionsHelper.fillCompilerArguments(from, args)
        args.moduleName = from.moduleName.orNull
    }

    internal fun syncOptionsAsConvention(
        from: org.jetbrains.kotlin.gradle.dsl.KotlinDotNetCompilerOptions,
        into: org.jetbrains.kotlin.gradle.dsl.KotlinDotNetCompilerOptions,
    ) {
        org.jetbrains.kotlin.gradle.dsl.KotlinCommonCompilerOptionsHelper.syncOptionsAsConvention(from, into)
        into.moduleName.convention(from.moduleName)
    }
}
