/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package kotlin.test

//
// NOTE: THIS FILE IS AUTO-GENERATED by the GenerateDotNetBootstrapKotlinTest.kt
// See: https://github.com/JetBrains/kotlin/tree/master/libraries/stdlib
//
/** Platform-specific construction of AssertionError with cause */
internal expect fun AssertionErrorWithCause(message: String?, cause: Throwable?): AssertionError
