/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package kotlin.test

//
// NOTE: THIS FILE IS AUTO-GENERATED by the GenerateDotNetBootstrapKotlinTest.kt
// See: https://github.com/JetBrains/kotlin/tree/master/libraries/stdlib
//
/**
 * Marks a function as a test.
 *
 * Only class member functions should be annotated with [Test],
 * the annotated function should not accept any parameters and its return type has to be [Unit].
 *
 * Applying [Test] to top-level, extension, or object member functions, functions accepting any parameters
 * or functions with a return type other than [Unit]
 * may lead to compilation or runtime errors, and behavior may vary on different targets.
 *
 * ```kotlin
 * import kotlin.test.*
 *
 * public class ArithmeticsTest {
 *     @Test
 *     fun addition() {
 *         assertEquals(4, 2 + 2)
 *     }
 * }
 * ```
 */
@Target(AnnotationTarget.FUNCTION)
public expect annotation class Test()
